#!/bin/bash

# Get ethernet adapter name
eth_interface=`ip link | awk -F: '$0 !~ "lo|vir|docker|wl|^[^0-9]"{print $2;getline}'`
echo Ethernet adaptor found: $eth_interface

echo Setting uo the lidar connection
echo Ethernet Internface used: $eth_interface 

ip addr flush dev $eth_interface
ip addr show dev $eth_interface

sudo ip addr add 10.5.5.1/24 dev $eth_interface

sudo ip link set $eth_interface up

ip addr show dev $eth_interface

read -p "Power up the lidar and connect it now, press enter when done."

# "&" at the end of commands is for running processed in parllel

sudo ptp4l -i $eth_interface -S -m &

sudo dnsmasq -C /dev/null -kd -F 10.5.5.50,10.5.5.100 -i $eth_interface --bind-dynamic &
